main: dev.rotator.Main
name: IslandKitPvP
version: 0.1
api-version: 1.20
commands:
  tester:
    description: "Testing stuff"
    usage: "§cI can't tell you the usage. Go ask rotator."
  kit:
    description: "Get a kit!"
    usage: "§cUsage: /kit <kitName>"
  setexp:
    description: "set player's xp"
    usage: "§cYou must be opped for this command. Please ask rotator if you're opped and it doesn't work."
  getexp:
    description: "get player's xp"
    usage: "§cYou must be opped for this command. Please ask rotator if you're opped and it doesn't work."